a = 12
b = 3
rezultat = a + b
print(f"{a} + {b} = {rezultat}")
rezultat = a - b
print(f"{a} - {b} = {rezultat}")
rezultat = a * b
print(f"{a} * {b} = {rezultat}")
rezultat = a / b
print(f"{a} / {b} = {rezultat}")
rezultat = a * b
print(f"{a} * {b} = {rezultat}")
